### PR TITLE
update to asp.net core 2.0

### PR DESCRIPTION
**Pull request by irriss**
update all nuget packages

### CODE REVIEW

**Comment by agrothe** [comment]
@irriss would you like to join these two aspnetcore arangodb projects? I can add you so you can merge pull requests and such.

**Comment by irriss** [comment]
@agrothe ok let's try

**Comment by agrothe** [comment]
@irriss See if you can merge your latest pull requests. Should have access.

**Comment by irriss** [comment]
it works! thanks

**Pull request merged**
